/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package marcaponto;
import java.sql.*;
/**
 *
 * @author vinib
 */
public class AlterInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form AlterInfoPanel
     */
    public AlterInfoPanel(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        lbErro.setVisible(false);
        dlgExcluir.setContentPane(new DeleteAccountPanel(this));
        dlgExcluir.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgExcluir = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfCPF = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfUsuario = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        lbErro = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        pfSenha = new javax.swing.JPasswordField();
        pfConfirmaSenha = new javax.swing.JPasswordField();
        btnExcluir = new javax.swing.JButton();

        dlgExcluir.setTitle("Excluir cadastro");
        dlgExcluir.setAlwaysOnTop(true);

        javax.swing.GroupLayout dlgExcluirLayout = new javax.swing.GroupLayout(dlgExcluir.getContentPane());
        dlgExcluir.getContentPane().setLayout(dlgExcluirLayout);
        dlgExcluirLayout.setHorizontalGroup(
            dlgExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dlgExcluirLayout.setVerticalGroup(
            dlgExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Usuário");

        jLabel3.setText("Senha");

        jLabel4.setText("CPF");

        jLabel5.setText("Telefone");

        jLabel6.setText("E-mail");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lbErro.setForeground(new java.awt.Color(255, 51, 0));
        lbErro.setText("lbErro");

        jLabel7.setText("Confirma senha");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir cadastro");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pfConfirmaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSalvar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbErro))
                        .addComponent(tfUsuario)
                        .addComponent(tfEmail)
                        .addComponent(tfTelefone)
                        .addComponent(tfCPF)
                        .addComponent(tfNome)
                        .addComponent(jLabel7)
                        .addComponent(pfSenha)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(lbErro)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        try
        {
            conn = ConexaoMySQL.conectarBanco();
            Statement st = conn.createStatement();
            
            ResultSet rs = st.executeQuery(
                "SELECT usuario FROM projeto_java.Usuarios WHERE usuario = \"" + tfUsuario.getText() + "\";"
            );
            if (rs.next() && !rs.getString("usuario").equals(mainFrame.username))
                throw new Exception("Nome de usuário já existe");
            
            //checar tamanho da senha
            if (pfSenha.getPassword().length < 8) {
                throw new Exception("Senha muito curta");
            }
            //checar se senhas batem
            if (!(new String(pfSenha.getPassword())).contentEquals(new String(pfConfirmaSenha.getPassword())))
                throw new Exception("Senhas não são iguais");
        
            //inserir novo usuario
            String sql = "update projeto_java.Usuarios ";
            sql += "set nome = \"" + tfNome.getText() + "\", ";
            sql += "cpf = \"" + tfCPF.getText() + "\", ";
            sql += "telefone = \"" + tfTelefone.getText() + "\", ";
            sql += "email = \"" + tfEmail.getText() + "\", ";
            sql += "usuario = \"" + tfUsuario.getText() + "\", ";
            sql += "senha = \"" + new String(pfSenha.getPassword()) + "\"";
            sql += "where id = " + mainFrame.userId + ";";
            st.executeUpdate(sql);
            
            mainFrame.nome = tfNome.getText();
            mainFrame.username = tfUsuario.getText();
            
            mainFrame.switchPanel(lastPanel);
        }
        catch (SQLException e)
        {
            System.out.println(e.getMessage());
        }
        catch (Exception e) {
            lbErro.setText(e.getMessage());
            lbErro.setVisible(true);
        }
        finally {
            if (conn != null) {
                try {
                    conn.close();
                }
                catch (SQLException e) {
                    System.out.println(e.getMessage());
                }
            }
        }
        tfNome.setText("");
        tfCPF.setText("");
        tfTelefone.setText("");
        tfEmail.setText("");
        tfUsuario.setText("");
        pfSenha.setText("");
        pfConfirmaSenha.setText("");
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        lastPanel = mainFrame.getLastPanel();
        Connection conn = null;
        try
        {
            conn = ConexaoMySQL.conectarBanco();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from projeto_java.Usuarios where id = " + mainFrame.userId);
            rs.next();
            tfNome.setText(rs.getString("nome"));
            tfCPF.setText(rs.getString("cpf"));
            tfTelefone.setText(rs.getString("telefone"));
            tfEmail.setText(rs.getString("email"));
            tfUsuario.setText(rs.getString("usuario"));
            pfSenha.setText(rs.getString("senha"));
            pfConfirmaSenha.setText(new String(pfSenha.getPassword()));
        }
        catch (SQLException e)
        {
            System.out.println(e.getMessage());
        }
        finally {
            if (conn != null) {
                try {
                    conn.close();
                }
                catch (SQLException e) {
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_formComponentShown

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        mainFrame.switchPanel(lastPanel);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        dlgExcluir.setVisible(true);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
        tfNome.setText("");
        tfCPF.setText("");
        tfTelefone.setText("");
        tfEmail.setText("");
        tfUsuario.setText("");
        pfSenha.setText("");
        pfConfirmaSenha.setText("");
    }//GEN-LAST:event_formComponentHidden
    
    public void excluirCadastro() {
        Connection conn = null;
        try {
            conn = ConexaoMySQL.conectarBanco();
            Statement st = conn.createStatement();
            st.executeUpdate("delete from projeto_java.Usuarios where id = " + mainFrame.userId);
            mainFrame.switchPanel("LOGIN");
        }
        catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        finally {
            if (conn != null) {
                try {
                    conn.close();
                }
                catch (SQLException e) {
                    System.out.println(e.getMessage());
                }
            }
        }
    }
    
    private String lastPanel;
    MainFrame mainFrame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JDialog dlgExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbErro;
    private javax.swing.JPasswordField pfConfirmaSenha;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField tfCPF;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfTelefone;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
